-- AlterTable
ALTER TABLE "AirdropClaim" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "DailyStats" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "FraudLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "MerkleJob" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Purchase" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ReviewQueue" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RiskLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "VestingClaim" ALTER COLUMN "id" DROP DEFAULT;
